### ISSUE TITLE
Need to add border on side panel.

### ISSUE THREAD

**Issue by hamster620** [carina-studio/ULogViewer#10]
<img width="121" alt="截圖 2022-02-08 下午8 57 18" src="https://user-images.githubusercontent.com/26860570/152991618-e1a42d7c-7108-49ad-b616-b29dd98a2f62.png">

**Comment by carina-studio** [comment]
https://github.com/carina-studio/ULogViewer/commit/1f80ab9fd132a0b2fb2caf0447650ee90b8a60fc
