### ISSUE TITLE
Feature request: Can you add apache logs support as well please?

### ISSUE THREAD

**Issue by reddyshyam** [carina-studio/ULogViewer#15]
Hi,

Good day! Great app by the way! I have a feature request if I am may please. Ideally I would like to drop apache logs, see, filter and analyse it. Would this be possible?

**Comment by reddyshyam** [comment]
> Hi @reddyshyam Could you help to provide a sample Apache log file so that I can provide a log profile based-on it. Thanks.

Hi @hamster620, 

Good day! Thanks for getting back and trying. Please find attached a sample log file. Hope this helps.
[access.zip](https://github.com/carina-studio/ULogViewer/files/9600342/access.zip)

**Comment by hamster620** [comment]
Hi @reddyshyam 
Here is a custom log profile based on the file you provided and documentation of Apache Access Log:
[ApacheAccessLog.json.zip](https://github.com/carina-studio/ULogViewer/files/9603160/ApacheAccessLog.json.zip)

You just need to download, extract and import .json file to your ULogViewer before using it. You can refer to [here](https://carinastudio.azurewebsites.net/ULogViewer/HowToReadAndParseLogs) if you want to modify or create your own log profile.

For any log file with unknown format, you can choose ```Raw Text In Files``` log profile to view content in file. It is also good to use ULogViewer as plain text viewer.

**Comment by reddyshyam** [comment]
> Hi @reddyshyam Here is a custom log profile based on the file you provided and documentation of Apache Access Log: [ApacheAccessLog.json.zip](https://github.com/carina-studio/ULogViewer/files/9603160/ApacheAccessLog.json.zip)
> 
> You just need to download, extract and import .json file to your ULogViewer before using it. You can refer to [here](https://carinastudio.azurewebsites.net/ULogViewer/HowToReadAndParseLogs) if you want to modify or create your own log profile.
> 
> For any log file with unknown format, you can choose `Raw Text In Files` log profile to view content in file. It is also good to use ULogViewer as plain text viewer.

Just perfect! Highly customisable. Thanks @hamster620. I really appreciate your help. 👍 🙏👏
