### ISSUE TITLE
体验问题

### ISSUE THREAD

**Issue by wzg1015** [carina-studio/ULogViewer#16]
1.  优化：文字筛选界面，宽度比较窄，有时多选时会不小心点击到删除按钮上。没有二次确认。
建议二选一：1.删除的二次确认（可以在选项里面配置是否开启）2.删除挪动到编辑内
2.需求：文字筛选如果多了，能否支持文件夹分组
3.优化：标记后的日志。在日志左侧大的界面点击该行日志时，会自动跳转到该日志的顶行。不符合预期。
4.优化：文字过滤器 创建时，不能直接输入正则，必须二次点击编辑才能输入。
5.需求：筛选的关键字能否支持高亮颜色，过滤器多了不好找

**Comment by hamster620** [comment]
@wzg1015 感謝您的建議，關於 1~3 點我們會加入下一版的設計考量，4 及 5 目前已經在 3.0 版本中改善。

**Comment by hamster620** [comment]
@wzg1015 關於第三點已經做了初步的行為修正，並發佈於 [2.0.20.403](https://github.com/carina-studio/ULogViewer/releases/tag/2.0.20.403)，其他的改善及修正將在 3.0 釋出，謝謝。

**Comment by wzg1015** [comment]
> @wzg1015 感謝您的建議，關於 1~3 點我們會加入下一版的設計考量，4 及 5 目前已經在 3.0 版本中改善。

长期使用，能极大提高分析效率。 第二点比较迫切，便于梳理知识和降低查找时间。我认为这个是个大亮点。

**Comment by hamster620** [comment]
@wzg1015 文字篩選分組功能已於 [3.0.1.524-dev](https://github.com/carina-studio/ULogViewer/releases/tag/3.0.1.524) 釋出，請更新後試用此功能，謝謝。
