### ISSUE TITLE
Marked entries showing in unrelated search and still when unmarked

### ISSUE THREAD

**Issue by sam-morin** [carina-studio/ULogViewer#18]
To reproduce:

- In Windows event log mode - 
1. Mark an entry with a color
2. Search for a string that does not exist
3. The marked entry is shown in the search result list, in this case it's the only result because the string does not exist
4. After unmarking the entry, it still stays in the search result

**Comment by carina-studio** [comment]
@sam-morin It is by design because we think all marked logs should be relatively important and we want to prevent user from lossing the log in filtered list just because unmarking it unexpectedly (maybe accedently clicking ```M``` key).

**Comment by sam-morin** [comment]
Ah okay I understand. Thank you!
