### ISSUE TITLE
3.0版本里为什么把日志显示模式分栏了

### ISSUE THREAD

**Issue by wzg1015** [carina-studio/ULogViewer#19]
最近升级新的3.0版本后，发现日志显示模式被整合到一个里面了。
但日志的显示模式切换是一个非常高频操作（找到关键日志后，查看对应日志上下文日志），之前的方式我觉得挺好的。
现在换成到一个栏目里面后，比之前多了3步操作（或者使用快捷方式）：1.点开   2.移动鼠标到预期选项   3.点击。比以前体验差很多。
我理解高频的操作就应该放独立按钮，而不应该以更多的方式展现。

**Comment by hamster620** [comment]
@wzg1015 我們這邊確實也有收到類似的回饋，將會考慮恢復原有的按鈕配置。

**Comment by hamster620** [comment]
於 [3.0.1.524-dev](https://github.com/carina-studio/ULogViewer/releases/tag/3.0.1.524) 版本恢復原設計。
