### ISSUE TITLE
NLog Log pattern example for this scenario

### ISSUE THREAD

**Issue by mubeda** [carina-studio/ULogViewer#20]
Hi there, could you please help me with the right log pattern to use in a template for this nlog.conf targets? 

This is the layout of the file based one:

layout="${longdate} ${level:uppercase=true:padding=5} - ${logger} - ${message} ${onexception:inner=${newline}${exception:format=tostring}}"/>

This is the one for the UPD logger:

layout="${log4jxmlevent:includeNLogData=true}"

Thank you so much

**Comment by hamster620** [comment]
@mubeda Please refer to [NLog Sample (GitHub).zip](https://github.com/carina-studio/ULogViewer/files/11468897/NLog.Sample.GitHub.zip). Hope it can help you.

**Comment by mubeda** [comment]
Thank you so much!
