### ISSUE TITLE
最新的3.0版本无法移除旧专业版授权

### ISSUE THREAD

**Issue by wzg1015** [carina-studio/ULogViewer#22]
公司电脑，每一次重启均会被ULogView 认为是一个新电脑。
导致 每次重启后，第一次 专业版授权 会被失效。但之前 点击确认   是可以移除旧的授权，所以就没管。
近期升级最新ULogViewer后，弹出提示框后(无法启用「ULogViewer 专业版」，请尝试再次启用。)，点确认直接退出了。
账号：wzg1015@hotmail.com

**Comment by wzg1015** [comment]
回退 [3.0.1.603-preview](https://github.com/carina-studio/ULogViewer/releases/tag/3.0.1.603) 正常

**Comment by hamster620** [comment]
@wzg1015 更新為 3.0 會需要重新授權是已知現象，因為授權所使用的識別碼有更新 (2.0 有其漏洞)。目前可以先不管原 2.0 的授權，待授權裝置個數超過時會有對應的畫面讓您刪除舊的裝置 (2.0)。

至於點擊 [確定] 後 ULogViewer 會直接退出的問題，需要請您協助使用「關於 ULogViewer」底部的「匯出應用程式日誌」將日誌匯出並提供給我們確認原因，謝謝。

**Comment by hamster620** [comment]
[3.0.3.620](https://github.com/carina-studio/ULogViewer/releases/tag/3.0.3.620) 修復了無法開啟專業版授權對話方塊的問題。
