### ISSUE TITLE
log filtering: show previous filters

### ISSUE THREAD

**Issue by jan831** [carina-studio/ULogViewer#26]
would be a nice feature, to have a history of the filters.  An optional list of previously used search expressions
![image](https://github.com/carina-studio/ULogViewer/assets/8938929/e4a03446-7dad-4bdc-8165-029967619c16)

**Comment by hamster620** [comment]
@jan831 Thanks for suggestion, currently you can navigate history of text filter by pressing ```Up```/```Down``` key on text filter input field. It is a feature which is too difficult to be discovered, so we need to have new UX for it.

Simply showing a popup may conflict with existing popup of regex syntax assistance. So we may add a button to show history of text filter and let user select.

**Comment by hamster620** [comment]
History of log text filters is now supported in [4.0.1.1222](https://github.com/carina-studio/ULogViewer/releases/tag/4.0.1.1222).
