### ISSUE TITLE
scrollable marked logs

### ISSUE THREAD

**Issue by jan831** [carina-studio/ULogViewer#27]
the marked items side pane has a max width of +- 20% of the total window size.

In our log files, the first 20 characters show the time, log level, thread name.   Navigating from the marked logs would only be useful if we can see the full log line.

So make the side pane scrollable, or allow it to take 50% of the available space

**Comment by hamster620** [comment]
In [4.0.1.1222](https://github.com/carina-studio/ULogViewer/releases/tag/4.0.1.1222) if there is no log property defined to be shown, than multiple lines can be shown for each log in **Marked logs** panel.
