### ISSUE TITLE
是否可以在 key log analysis rule 中自定义时间格式

### ISSUE THREAD

**Issue by aibitos** [carina-studio/ULogViewer#29]
当前在使用 Key log analysis 功能时，想在展示结果里添加时间戳，会如下方式写
```
{Timestamp} xxxx
```
当分析结果展示出来时会显示
```
1/26/2024 7:00:00 PM xxxx
```
分析结果展示的字符宽度有限，而这个时间展示太占空间，希望可以自定义 Timestamp 的 format

**Comment by hamster620** [comment]
@aibitos 可以的，使用 ```{Timestamp:日期時間格式}``` 即可指定輸出格式，例如 ```{Timestamp:yy-MM-dd}``` 就會輸出 ```24-01-26```.
