### ISSUE TITLE
Need help to parse custom log pattern

### ISSUE THREAD

**Issue by GreenNeon** [carina-studio/ULogViewer#31]
I have a log file with a custom pattern like below.
```
[2024-02-19T16:55:18.296] [DEBUG] product details v2 
 |-> get products - Total Article Not In DB: 0
[2024-02-19T16:55:19.327] [WARN] customers - Error on customers, customers doesnt have 'something'! {
  anything_goes: [ '0000600186' ],
  stack: 'Error\n' +
    '    at getStack (D:\\Repository\\something\\service\\custSapOnDB\\fnsomething.js:6:11)\n' +
    '    at module.exports (D:\\Repository\\something\\service\\custSapOnDB\\fnsomething.js:16:17)\n' +
    '    at Object.module.exports [as shiptoV2] (D:\\Repository\\something\\graphql\\resolver\\catalog\\shipToV2.js:159:28)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:94:5)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async graphqlMiddleware (D:\\Repository\\something\\node_modules\\express-graphql\\index.js:125:26)'
}
```
I can get the first line with 
```
.*^(\[(?<Timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+)\])\s\[(?<Level>\w+)\]\s(?<Title>.*)
```
But how to get the next line??

**Comment by hamster620** [comment]
Hi @GreenNeon, you just need to define 2nd log pattern and set it as ```skippable```, maybe set as ```repeatable``` also if more lines are possible.
![image](https://github.com/carina-studio/ULogViewer/assets/26860570/54cb7ef7-ee57-4380-957e-88ea62df7dd3)
![image](https://github.com/carina-studio/ULogViewer/assets/26860570/0839e181-4160-4c11-b8c0-09d13132fce3)

Here is a sample log profile based-on the log you provided:
[GitHub#31.json](https://github.com/carina-studio/ULogViewer/files/14360400/GitHub.31.json)

**Comment by GreenNeon** [comment]
Work great, I understand now. 
Thank you for your response 😁.
