### ISSUE TITLE
[Question] Does this LogViewer support Multi-line Log lines?

### ISSUE THREAD

**Issue by En3Tho** [carina-studio/ULogViewer#33]
I stumbled upon htis log viewer while examining Avalonia's showcase and it looked very interesting. Some of our legacy apps still output logs to files in a specific per-app format. Often log "lines" (or rather entries) contain newlines. How do I match those?

For example given this simplified format as an example `|{TimeStamp}|{Level}|{Message}\n    {Variables}` may result in something like this:
```
|TimeStamp|Level|Some message   
    ....
    ....
    that actually can be multiline
    Var=1 Var2= Var3=
|TimeStamp|Level|.... Next entry
```

Can this be possible to match using this viewer?

**Comment by hamster620** [comment]
@En3Tho Sure it supports parsing log with multiple lines. You can refer to #31 for defining log patterns for multiple lines, thanks.

**Comment by En3Tho** [comment]
@hamster620 Thank you!
