### ISSUE TITLE
Multiline message starts with empty line

### ISSUE THREAD

**Issue by sutr90** [carina-studio/ULogViewer#37]
I have following log pattern:
`
2024-03-07 14:46:42.089 [http-nio-8181-exec-17] WARN  com.example.logger.Logger [Context: ctx]
CONFIGURATION_ERROR PROPERTY_ERROR
User message: Properties have error
Technical message: Properties have error
Solution: Please contact support
Impact: Impact
`
And I have successfully created patterns to match this almost as I need using following: [multiline.json](https://github.com/carina-studio/ULogViewer/files/14601044/multiline.json)

The only issue now is, that the multiline message starts with empty line break, and I have no idea how to get rid of it.
![image](https://github.com/carina-studio/ULogViewer/assets/1327101/f588fb32-f560-4873-9f12-67f23936f1c5)

If there would be a message on the first line in my sample, with the timestamp. It would work as I need, but I cannot change the log format...

**Comment by hamster620** [comment]
@sutr90 it seems that this is a limitation in current version, we will try removing the first empty line and release in next version.

**Comment by sutr90** [comment]
Thank you for the quick reply!

**Comment by hamster620** [comment]
Fixed in [4.0.9.331](https://github.com/carina-studio/ULogViewer/releases/tag/4.0.9.331).
