### ISSUE TITLE
Question: how to get "Added log files" tab visible when running local dev build

### ISSUE THREAD

**Issue by acastruc** [carina-studio/ULogViewer#47]
I have a registered copy of ULogViewer. When I run it I see multiple docked windows on the right of application window:
<img width="68" alt="image" src="https://github.com/user-attachments/assets/24aad927-f955-48fd-82dc-667cebcb4d90">

When I build + run from source locally, I am missing some of these tabs ("Added log files" in this case)
<img width="85" alt="image" src="https://github.com/user-attachments/assets/dd940393-8021-4640-bbf2-6337e8d76f7e">

What do I need to do to have my local debug build use the same configuration as my "registered" copy?

**Comment by hamster620** [comment]
@acastruc Log Analysis and Log Files features are not part of open source project. I know its not convenient to you but currently you can just develop without these features.

**Comment by acastruc** [comment]
@hamster620 ok, no problem. Thanks for the response.
