### ISSUE TITLE
Debug and Trace levels are the same color (blue) making it unnecessarily difficult to differentiate.

### ISSUE THREAD

**Issue by acastruc** [carina-studio/ULogViewer#50]
I created a simple profile that included mapping for both Debug and Trace level logs.
The application assigns both the same color of blue - why? Wouldn't it be more useful to differentiate?
Or better yet let me edit the color (though I see someone else suggested that earlier)

OS: mac 14 M2
Steps
1. Create profile
2. Add mapping for both Debug and Trace level.
3. Load a log file containing both Debug and Trace logs

Result:
App assigns both to use the same color, unlike every other log level.
Example
![image](https://github.com/user-attachments/assets/b5538fb7-53a8-413a-a8e5-71e1cc73f065)

**Comment by hamster620** [comment]
Colors are adjested in [5.0.0.921-dev](https://github.com/carina-studio/ULogViewer/releases/tag/5.0.0.921).

**Comment by acastruc** [comment]
Thank you! Much appreciated!
