### ISSUE TITLE
Waiting for features/bug fixes

### ISSUE THREAD

**Issue by acastruc** [carina-studio/ULogViewer#51]
Our company wants to use this tool, we purchased 10 licenses. However in order to be effective we are still waiting for 
1. exclusion text filters
2. separate colors for trace vs debug logs
3. ability to select a log line and remove all logs that occur before said selected log

1, 2 above have been implemented but not released as of 4.0.13.1002. 
I have implemented 3 but have not created PR.
I realize you provided a dev build of the 5.0.x release but only for mac - we are need mac and windows. Not to mention we'd have to use our licenses on the 5.0 dev build since we require some of the locked features.
In the very least, can you provide Windows binaries of the dev 5 build? We can use our licenses on that for the time being.

**Comment by hamster620** [comment]
@acastruc The 1st and 2nd features will be pulled in to ULogViewer 4.1. We will release ULogViewer 4.1 preview soon. You can enable ```Accept non-stable application update``` in the application options to receive notification in ULogViewer 4.0:
![image](https://github.com/user-attachments/assets/a76fbb7c-d7f2-4bc3-8b11-a786fd5fcb5b)

For the 3rd feature, it is more complex to design and implement. So it won't be available in a short time and will be part of ULogViewer 5.0.

**Comment by acastruc** [comment]
@hamster620 Thanks for the update, we look forward to trying 4.1
I will submit a PR with what I have for 3 soon
